spring.application.name=backendmongo
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/ironfit

# JWT
security.jwt.secret=IronFit_2026_Sem5_JWT_Secret_Super_Largo_123456789
security.jwt.expiration-minutes=120